---
title: "Dose response figures"
author: "Yanelli Nunez"
date: "3/01/2022"
output:
 html_document:
    toc: TRUE
    toc_float: TRUE
    code_folding: hide
editor_options: 
  chunk_output_type: console
---


Objective:  

Create Table 1 and Table 2 for manuscript

```{r include=FALSE}

rm(list=ls())

# 1a Declare root directory

project.folder <- paste0(print(here::here()),'/')

# add folder locations
source(paste0(project.folder,'0_00_create_folder_structure.R'))

# add file locations
source(paste0(file.locations.folder,'external_file_locations.R'))

# load packages
source(paste0(packages.folder,'packages_to_load.R'))

# load functions
 source(paste0(code.folder, 'models/functions.R'))

# load data
source(paste0(code.folder, 'data_loading.R'))

```


## 1. Manuscript Table 1

Estimate mean and IQR for the demographic variables and confounding variables

```{r}


table_1 <- data_full %>%
  dplyr::filter(year %in% c("1970", "1980", "1990", "2000")) %>%
  dplyr::select(year, perc_white, perc_black, perc_asian, perc_nativ, perc_hisp_org, perc_pvert, perc_unemp, fam_incom_adjs, propty_val_adjs, pop_density, urbanicity) %>%
  mutate(fam_incom_adjs = fam_incom_adjs/1000,
         propty_val_adjs = propty_val_adjs/1000) %>%
 # drop_na(so2_industry) %>% # removing the counties for which we do not have exposure (5 counties)
  droplevels() %>%
  gtsummary::tbl_summary(#missing = "no",
              label = list(perc_white ~ "% White",
                           perc_black ~ "% Black",
                           perc_asian ~ "% Asian",
                           perc_nativ ~ "% American Indian",
                           perc_hisp_org ~ "% Hispanic",
                           perc_pvert ~ "% Poverty",
                           perc_unemp ~ "% Unemployment",
                           fam_incom_adjs ~ "Family Income (X$1000)",
                           propty_val_adjs ~ "Property Value (X$1000)",
                           pop_density ~ "Population Density",
                           urbanicity ~ "Urbanicity"),
              by = year,
              statistic = list(all_continuous() ~ "{mean} ({p25}, {p75})",
                               all_categorical() ~ "{n} ({p}%)"),
              digits =    list(all_continuous() ~ 1,
                               all_categorical() ~ 1))
             # add_overall() %>%
 # bold_labels()

# save table
# no need to run because code will overwrite the already saved one
#table_1 %>%
 # gtsummary::as_flex_table() %>%
  #flextable::save_as_docx(path = paste0(figures.folder,'table_2_indep_var.docx'))

```

## 2. Manuscript Table 2: 

Estimate mean and IQR for the emission for all study years

```{r}

table_2 <- data_full %>%
  dplyr::filter(year %in% c("1970", "1980", "1990", "2000", "2010")) %>%
  dplyr::select(year, so2_industry, so2_ener, nox_ener, nh3_agric, nox_trans, oc_residential, nox_commercial) %>%
  drop_na(so2_industry) %>% # removing the counties for which we do not have exposure (5 counties)
  droplevels() %>%
  gtsummary::tbl_summary(#missing = "no",
              label = list(so2_industry ~ "Industry: SO2",
                           so2_ener ~ "Energy: SO2",
                           nox_ener ~ "Energy: NOx",
                           nh3_agric ~ "Agriculture: NH3",
                           nox_trans ~ "Transport: NOx",
                           oc_residential ~ "Residential: OC",
                           nox_commercial ~ "Commercial: NOx"),
              by = year,
              statistic = list(all_continuous() ~ "{mean} ({p25}, {p75})",
                               all_categorical() ~ "{n} ({p}%)"),
              digits =    list(all_continuous() ~ 1,
                               all_categorical() ~ 1))
             # add_overall() %>%
 # bold_labels()

# save table
# no need to run because code will overwrite the already saved one
#table_2 %>%
#  gtsummary::as_flex_table() %>%
#  flextable::save_as_docx(path = paste0(figures.folder,'table_2_emissions_summ.docx'))
```

## 3. Manuscript Table 3: 

Estimate mean and IQR for change in emissions  from one decennial to next

```{r}

nox_energy_tb <- nox_energy %>%
  dplyr::select(year, gisjoin, nox_energy_relat_chg)

so2_energy_tb <- so2_energy %>%
  dplyr::select(year, gisjoin, so2_energy_relat_chg)

so2_inds_tb <- so2_inds %>%
  dplyr::select(year, gisjoin, so2_indus_relat_chg)

tb3_prep <-  data_master %>%
  dplyr::select(year, gisjoin, county, state, nox_trans_relat_chg, nh3_agric_relat_chg, oc_resid_relat_chg, nox_commer_relat_chg) %>%
  full_join(., nox_energy_tb) %>%
  full_join(., so2_energy_tb) %>%
  full_join(., so2_inds_tb) 

summary(tb3_prep)                                                                                                                                

```


### 3a. Build table 3

```{r}

table_3a <- tb3_prep %>%
  dplyr::select(-year, -state, -county, -gisjoin, so2_indus_relat_chg, so2_energy_relat_chg, nox_energy_relat_chg, nh3_agric_relat_chg, nox_trans_relat_chg, oc_resid_relat_chg, nox_commer_relat_chg) %>%
  gtsummary::tbl_summary(missing = "no",
              label = list(so2_indus_relat_chg ~ "Industry: SO2",
                           so2_energy_relat_chg ~ "Energy: SO2",
                           nox_energy_relat_chg ~ "Energy: NOx",
                           nh3_agric_relat_chg ~ "Agriculture: NH3",
                           nox_trans_relat_chg ~ "Transport: NOx",
                           oc_resid_relat_chg ~ "Residential: OC",
                           nox_commer_relat_chg ~ "Commercial: NOx"),
              statistic = list(all_continuous() ~ "{mean}"),
                               #all_categorical() ~ "{n} ({p}%)"),
              digits =    list(all_categorical() ~ 1,
                               all_continuous() ~ 1)) %>%
  modify_header(stat_0 ~ "**Mean % Change**")

 table_3b <- tb3_prep %>%
  dplyr::select(-year, -state, -county, -gisjoin, so2_indus_relat_chg, so2_energy_relat_chg, nox_energy_relat_chg, nh3_agric_relat_chg, nox_trans_relat_chg, oc_resid_relat_chg, nox_commer_relat_chg) %>%
  gtsummary::tbl_summary(missing = "no",
              label = list(
                           so2_indus_relat_chg ~ "Industry: SO2",
                           so2_energy_relat_chg ~ "Energy: SO2",
                           nox_energy_relat_chg ~ "Energy: NOx",
                           nh3_agric_relat_chg ~ "Agriculture: NH3",
                           nox_trans_relat_chg ~ "Transport: NOx",
                           oc_resid_relat_chg ~ "Residential: OC",
                           nox_commer_relat_chg ~ "Commercial: NOx"),
              statistic = list(all_continuous() ~ "{p25}, {p75}"),
                               #all_categorical() ~ "{n} ({p}%)"),
              digits =    list(all_categorical() ~ 1,
                               all_continuous() ~ 1)) %>%
  modify_header(stat_0 ~ "**IQR**")


table_3 <- tbl_merge(list(table_3a, table_3b)) %>%
  modify_footnote(everything() ~ NA_character_) %>%
  modify_spanning_header(everything() ~ NA_character_)

# save table
# no need to run
#table_3 %>%
# gtsummary::as_flex_table() %>%
#  flextable::save_as_docx(path = paste0(figures.folder,'table_3_change.docx'))

```
