---
title: "Regional analysis plot"
author: "Yanelli Nunez"
date: "4/15/2022"
output:
 html_document:
    toc: TRUE
    toc_float: TRUE
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

*Objective:* 

The code produces Supplementary Fig. 4 and 5

Note: this figure uses the results produced in 'y_03_sensitiv_regional_models.rmd' from the models folder

```{r include=FALSE}

rm(list=ls())

# 1a Declare root directory
project.folder <- paste0(print(here::here()),'/')

# add folder locations
source(paste0(project.folder,'0_00_create_folder_structure.R'))

# add file locations
source(paste0(file.locations.folder,'external_file_locations.R'))

# load packages
source(paste0(packages.folder,'packages_to_load.R'))

# load functions
source(paste0(code.folder, 'models/functions.R'))

# load data
source(paste0(code.folder, 'data_loading.R'))

```

## 1. Load data

```{r}

models_regional_eco <- readRDS(paste0(yanelli_external, "results_updated/sensit_analys_models_regional_eco.rds"))

models_regional_race <- readRDS(paste0(yanelli_external, "results_updated/sensit_analys_models_regional_race.rds"))

models_national <- readRDS(paste0(yanelli_external, "results_updated/models_linear.rds"))

```

## 2. Adjust axis

### 2a. Family Income

```{r}

# Transport: NOx
models_regional_eco_1 <- models_regional_eco$plots[[1]] + scale_x_continuous(labels=function(x)x/1000, breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000))
models_regional_eco_2 <- models_regional_eco$plots[[2]] + scale_x_continuous(labels=function(x)x/1000, breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000))
models_regional_eco_3 <- models_regional_eco$plots[[3]] + scale_x_continuous(labels=function(x)x/1000, breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000))
models_regional_eco_4 <- models_regional_eco$plots[[4]] + scale_x_continuous(labels=function(x)x/1000, breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000))
models_regional_eco_5 <- models_regional_eco$plots[[5]] + scale_x_continuous(labels=function(x)x/1000, breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000))
models_regional_eco_6 <- models_regional_eco$plots[[6]] + scale_x_continuous(labels=function(x)x/1000, breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000))
models_regional_eco_7 <- models_regional_eco$plots[[7]] + scale_x_continuous(labels=function(x)x/1000, breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000))
models_regional_eco_8 <- models_regional_eco$plots[[8]] + scale_x_continuous(labels=function(x)x/1000, breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000))


# Industry: SO2
models_regional_eco_9 <- models_regional_eco$plots[[9]] + scale_x_continuous(labels=function(x)x/1000, breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000))
models_regional_eco_10 <- models_regional_eco$plots[[10]] + scale_x_continuous(labels=function(x)x/1000, breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000))
models_regional_eco_11 <- models_regional_eco$plots[[11]] + scale_x_continuous(labels=function(x)x/1000, breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000))
models_regional_eco_12 <- models_regional_eco$plots[[12]] + scale_x_continuous(labels=function(x)x/1000, breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000))
models_regional_eco_13 <- models_regional_eco$plots[[13]] + scale_x_continuous(labels=function(x)x/1000, breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000))
models_regional_eco_14 <- models_regional_eco$plots[[14]] + scale_x_continuous(labels=function(x)x/1000, breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000))
models_regional_eco_15 <- models_regional_eco$plots[[15]] + scale_x_continuous(labels=function(x)x/1000, breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000))
models_regional_eco_16 <- models_regional_eco$plots[[16]] + scale_x_continuous(labels=function(x)x/1000, breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000))

```

## 3. Plots

### 3a. Transportation: NOx

```{r}

pdf(file = "transport_nox_reg.pdf", width = 14, height = 15)            
 grid.arrange(# family income
              models_regional_eco_1,
              models_regional_eco_2,
              models_regional_eco_3,
              models_regional_eco_4,
              models_regional_eco_5,
              models_regional_eco_6,
              models_regional_eco_7,
              models_regional_eco_8,
              
              # Perc  Black
              models_regional_race$plots_black[[1]],
              models_regional_race$plots_black[[2]],
              models_regional_race$plots_black[[3]],
              models_regional_race$plots_black[[4]],
              models_regional_race$plots_black[[5]],
              models_regional_race$plots_black[[6]],
              models_regional_race$plots_black[[7]],
              models_regional_race$plots_black[[8]],
              
              # Perc White
              models_regional_race$plots_white[[1]],
              models_regional_race$plots_white[[2]],
              models_regional_race$plots_white[[3]],
              models_regional_race$plots_white[[4]],
              models_regional_race$plots_white[[5]],
              models_regional_race$plots_white[[6]],
              models_regional_race$plots_white[[7]],
              models_regional_race$plots_white[[8]],
             
             nrow = 6, ncol = 4)
             #left = gridtext::richtext_grob("Transport: NO<sub>x</sub> (% chg)", rot=90,
           #  gp=gpar(fontsize=15,font=8)))
dev.off() 


```


### 3b. Industry: SO2

```{r}

pdf(file = "Industry_so2_reg.pdf", width = 14, height = 15)            
 grid.arrange(# family income
              models_regional_eco_9,
              models_regional_eco_10,
              models_regional_eco_11,
              models_regional_eco_12,
              models_regional_eco_13,
              models_regional_eco_14,
              models_regional_eco_15,
              models_regional_eco_16,
              
              # Perc  Black
              models_regional_race$plots_black[[9]],
              models_regional_race$plots_black[[10]],
              models_regional_race$plots_black[[11]],
              models_regional_race$plots_black[[12]],
              models_regional_race$plots_black[[13]],
              models_regional_race$plots_black[[14]],
              models_regional_race$plots_black[[15]],
              models_regional_race$plots_black[[16]],
              
              # Perc White
              models_regional_race$plots_white[[9]],
              models_regional_race$plots_white[[10]],
              models_regional_race$plots_white[[11]],
              models_regional_race$plots_white[[12]],
              models_regional_race$plots_white[[13]],
              models_regional_race$plots_white[[14]],
              models_regional_race$plots_white[[15]],
              models_regional_race$plots_white[[16]],
             
             nrow = 6, ncol = 4)
             #left = gridtext::richtext_grob("Transport: NO<sub>x</sub> (% chg)", rot=90,
           #  gp=gpar(fontsize=15,font=8)))
dev.off() 


```



```{r}

### checking some model stuff
model_test <- gamm4::gamm4(so2_indus_relat_chg ~ s(perc_black) +
                                 #s(perc_white) +
                                Ns(perc_white, df = 4, ref = 87.58) +
                                s(pop_density) +
                                urbanicity +
                                year,
                 random = ~(1|state/gisjoin), data = so2_inds)

summary(model_test[[2]])
plot(model_test[[2]])
  

```

